import React, { useState } from 'react';
import { useAppContext } from '../utils/AppContext';
import { formatINR } from '../utils/mockData';
import { ArrowUpRight, TrendingUp, Users, Wallet, BadgeCheck, X, Building, PieChart as PieChartIcon, Search, Lightbulb, Target, Trophy, Clock } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Cell, ResponsiveContainer, Tooltip, Legend } from 'recharts';
import { Business } from '../types';

import { getBlueTickBusinessIds } from '../utils/blueTick';

export default function Dashboard() {
  const { state } = useAppContext();
  const [selectedBusiness, setSelectedBusiness] = useState<Business | null>(null);
  const [searchTerm, setSearchTerm] = useState('');

  // Calculate stats
  const totalBusinesses = state.businesses.length;
  const totalInvestors = state.investors.length;
  
  const totalFundingRequired = state.businesses
    .filter(b => b.status === 'listed')
    .reduce((sum, b) => sum + b.fundingRequired, 0);

  const totalCommissions = 
    state.businesses.reduce((sum, b) => sum + b.registrationCommissionPaid, 0) +
    state.investments.reduce((sum, inv) => {
      const upfront = inv.adminCommissionInvestor + inv.adminCommissionBusiness;
      const settlement = (inv.status === 'completed' && inv.payoutDetails) ? inv.payoutDetails.rmasCommission : 0;
      return sum + upfront + settlement;
    }, 0);

  const stats = [
    { label: 'Total RMAS Commissions', value: formatINR(totalCommissions), icon: TrendingUp, positive: true },
    { label: 'Registered Businesses', value: totalBusinesses, icon: Wallet, positive: false },
    { label: 'Total Investors', value: totalInvestors, icon: Users, positive: false },
    { label: 'Funding Needed (Listed)', value: formatINR(totalFundingRequired), icon: ArrowUpRight, positive: false },
  ];

  // Top Businesses by Interest Rate
  const topBusinesses = [...state.businesses]
    .sort((a, b) => b.interestRate - a.interestRate)
    .filter(b => b.name.toLowerCase().includes(searchTerm.toLowerCase()) || b.ownerName.toLowerCase().includes(searchTerm.toLowerCase()));

  // Top Performing / Blue Tick Businesses (High Investment & High Returns)
  const businessesWithStats = state.businesses.map(b => {
    const bizInvs = state.investments.filter(i => i.businessId === b.id);
    const totalInv = bizInvs.reduce((sum, inv) => sum + inv.amount, 0);
    const totalRet = bizInvs.filter(i => i.status === 'completed').reduce((sum, inv) => {
      const p = inv.payoutDetails;
      return sum + (p ? (p.totalCredited + p.rmasCommission + p.happyIncomeTax) : 0);
    }, 0);
    return { ...b, totalInv, totalRet };
  });

  // Data Analysis Setup
  const highestInvested = [...businessesWithStats].sort((a, b) => b.totalInv - a.totalInv)[0];
  const highestProfit = [...businessesWithStats].sort((a, b) => b.totalRet - a.totalRet)[0];
  const untappedBusinesses = businessesWithStats.filter(b => b.totalInv === 0);
  const newlyListed = [...state.businesses].reverse().slice(0, 3); // Since they are appended
  
  const blueTickBusinessIds = getBlueTickBusinessIds(state.businesses, state.investments);

  const blueTickBusinesses = businessesWithStats
    .filter(b => blueTickBusinessIds.has(b.id))
    .sort((a, b) => b.totalRet - a.totalRet)
    .slice(0, 4)
    .filter(b => b.name.toLowerCase().includes(searchTerm.toLowerCase()) || b.ownerName.toLowerCase().includes(searchTerm.toLowerCase()));

  const otherBusinesses = topBusinesses.filter(b => !blueTickBusinessIds.has(b.id));

  const getTime = (id: string) => parseInt(id.replace(/\D/g, '')) || 0;

  const recentFilteredInvestments = state.investments.slice()
    .sort((a, b) => getTime(b.id) - getTime(a.id))
    .filter(inv => {
      const business = state.businesses.find(b => b.id === inv.businessId);
      const investor = state.investors.find(i => i.id === inv.investorId);
      const match = searchTerm.toLowerCase();
      return business?.name.toLowerCase().includes(match) || investor?.name.toLowerCase().includes(match);
  });

  // Business Analytics Details
  const renderBusinessDetails = (business: Business) => {
    const bizInvestments = state.investments.filter(i => i.businessId === business.id);
    
    const totalInvested = bizInvestments.reduce((sum, inv) => sum + inv.amount, 0);
    const fundingRemaining = Math.max(0, business.fundingRequired - totalInvested);
    const fundingPercentage = business.fundingRequired > 0 ? (totalInvested / business.fundingRequired) * 100 : 0;

    // Calculate profits
    let expectedProfitToPay = 0;
    let actualProfitPaid = 0;

    bizInvestments.forEach(inv => {
      if (inv.status === 'completed') {
        const payout = inv.payoutDetails;
        if (payout) {
          // Profit paid is what total credited is minus the invested amount, and plus taxes/fees if we consider profit generated by business.
          // Or we just display the raw profit derived from payout.
          // A simple way: Profit paid to investor is just the gross profit before deductions, since that's what the business paid!
          const grossPayout = payout.totalCredited + payout.rmasCommission + payout.happyIncomeTax;
          actualProfitPaid += (grossPayout - inv.amount);
        } else {
          // fallback
          actualProfitPaid += inv.amount * ((inv.interestRate || business.interestRate) / 100);
        }
      } else {
        expectedProfitToPay += inv.amount * ((inv.interestRate || business.interestRate) / 100);
      }
    });

    const fundingData = [
      { name: 'Invested', value: totalInvested, color: '#16a34a' }, // Green
      { name: 'Remaining', value: fundingRemaining, color: '#e5e7eb' } // Gray
    ];

    const profitData = [
      { name: 'Paid Back (Profit)', value: actualProfitPaid, color: '#3b82f6' }, // Blue
      { name: 'Expected (Pending)', value: expectedProfitToPay, color: '#f59e0b' } // Amber
    ];

    return (
      <div className="fixed inset-0 z-50 flex items-center justify-center bg-gray-900/60 p-4">
        <div className="bg-white rounded-xl w-full max-w-4xl max-h-[90vh] overflow-y-auto shadow-2xl">
          <div className="sticky top-0 bg-white border-b border-gray-100 p-4 flex justify-between items-center z-10">
            <div>
              <div className="flex items-center space-x-2">
                <h3 className="font-bold text-xl text-black">
                  {business.name}
                </h3>
                {blueTickBusinessIds.has(business.id) && <BadgeCheck size={20} className="text-blue-500" />}
              </div>
              <p className="text-[11px] font-medium text-gray-500 mt-0.5 tracking-wide uppercase">
                {blueTickBusinessIds.has(business.id) ? "RMAS Verified & High Profit Business" : "RMAS Registered Business"}
              </p>
            </div>
            <button 
              onClick={() => setSelectedBusiness(null)}
              className="p-1.5 hover:bg-gray-100 rounded-full text-gray-500 transition-colors"
            >
              <X size={20} />
            </button>
          </div>
          
          <div className="p-5 space-y-6">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
              <div className="bg-gray-50 p-3 rounded-lg border border-gray-100">
                <p className="text-[10px] font-bold text-gray-500 uppercase tracking-widest">Total Required</p>
                <p className="text-lg font-black text-black mt-1">{formatINR(business.fundingRequired)}</p>
              </div>
              <div className="bg-green-50 p-3 rounded-lg border border-green-100">
                <p className="text-[10px] font-bold text-green-700 uppercase tracking-widest">Total Invested</p>
                <p className="text-lg font-black text-green-700 mt-1">{formatINR(totalInvested)}</p>
              </div>
              <div className="bg-blue-50 p-3 rounded-lg border border-blue-100">
                <p className="text-[10px] font-bold text-blue-700 uppercase tracking-widest">Profit Paid</p>
                <p className="text-lg font-black text-blue-700 mt-1">{formatINR(actualProfitPaid)}</p>
              </div>
              <div className="bg-amber-50 p-3 rounded-lg border border-amber-100">
                <p className="text-[10px] font-bold text-amber-700 uppercase tracking-widest">Expected Return</p>
                <p className="text-lg font-black text-amber-700 mt-1">{formatINR(expectedProfitToPay)}</p>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Funding Chart */}
              <div className="border border-gray-200 rounded-lg p-4 bg-white shadow-sm">
                <h4 className="font-bold text-black mb-4 text-center flex items-center justify-center space-x-2 text-sm">
                  <PieChartIcon size={16} />
                  <span>Funding Status ({fundingPercentage.toFixed(1)}%)</span>
                </h4>
                <div className="h-56">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={fundingData} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}>
                      <CartesianGrid strokeDasharray="3 3" vertical={false} />
                      <XAxis dataKey="name" tick={{ fontSize: 12 }} />
                      <YAxis tickFormatter={(value) => formatINR(value)} width={80} tick={{ fontSize: 12 }} />
                      <Tooltip formatter={(value: number) => formatINR(value)} cursor={{ fill: 'transparent' }} />
                      <Bar dataKey="value" radius={[4, 4, 0, 0]} maxBarSize={60}>
                        {fundingData.map((entry, index) => (
                          <Cell key={`cell-${index}`} fill={entry.color} />
                        ))}
                      </Bar>
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </div>

              {/* Returns Chart */}
              <div className="border border-gray-200 rounded-lg p-4 bg-white shadow-sm">
                <h4 className="font-bold text-black mb-4 text-center flex items-center justify-center space-x-2 text-sm">
                  <TrendingUp size={16} />
                  <span>Profit & Returns</span>
                </h4>
                <div className="h-56">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={profitData} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}>
                      <CartesianGrid strokeDasharray="3 3" vertical={false} />
                      <XAxis dataKey="name" tick={{ fontSize: 12 }} />
                      <YAxis tickFormatter={(value) => formatINR(value)} width={80} tick={{ fontSize: 12 }} />
                      <Tooltip formatter={(value: number) => formatINR(value)} cursor={{ fill: 'transparent' }} />
                      <Bar dataKey="value" radius={[4, 4, 0, 0]} maxBarSize={60}>
                        {profitData.map((entry, index) => (
                          <Cell key={`cell-${index}`} fill={entry.color} />
                        ))}
                      </Bar>
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </div>
            </div>

            {/* Advice Panel */}
            <div className="bg-gray-900 text-white p-4 rounded-lg relative overflow-hidden">
              <div className="relative z-10">
                <h4 className="font-bold text-sm mb-1.5 flex items-center space-x-2">
                  <BadgeCheck size={16} className="text-blue-400 flex-shrink-0" />
                  <span className="truncate">RMAS Investment Insight</span>
                </h4>
                <p className="text-gray-300 text-xs leading-relaxed max-w-2xl text-justify break-words whitespace-normal">
                  આ કંપની RMAS દ્વારા ચકાસાયેલ છે. અહીં તમે <strong>{business.interestRate}%</strong> વળતર સાથે સુરક્ષિત રોકાણ કરી શકો છો. અત્યાર સુધી લોકોએ <strong>{formatINR(totalInvested)}</strong> જેટલું વિશ્વાસપાત્ર ઇન્વેસ્ટમેન્ટ કર્યું છે. નવા રોકાણકારો માટે આ એક સુરક્ષિત વિકલ્પ સાબિત થઇ શકે છે.
                </p>
              </div>
              <Building size={80} className="absolute -right-4 -bottom-4 text-white opacity-5" />
            </div>

          </div>
        </div>
      </div>
    );
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-4">
        <div>
          <h2 className="text-xl font-bold text-black tracking-tight">System Overview</h2>
          <p className="text-xs text-gray-500 mt-1">Key metrics and top investment opportunities for Radhika Ma Service.</p>
        </div>
        <div className="relative w-full md:w-72">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} />
          <input 
            type="text"
            placeholder="Search businesses or investors..."
            className="w-full pl-9 pr-4 py-1.5 text-sm border border-black rounded-sm focus:ring-2 focus:ring-black focus:outline-none transition-shadow font-medium"
            value={searchTerm}
            onChange={e => setSearchTerm(e.target.value)}
          />
        </div>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {stats.map((stat, i) => {
          const Icon = stat.icon;
          return (
            <div key={i} className="bg-white p-4 rounded-lg border border-gray-200 shadow-sm">
              <div className="flex flex-col">
                <div className="w-8 h-8 rounded-lg bg-gray-50 flex items-center justify-center mb-3">
                  <Icon size={16} className="text-black" />
                </div>
                <div>
                  <p className="text-[11px] font-bold text-gray-500 mb-1 tracking-wide uppercase leading-tight">{stat.label}</p>
                  <h3 className={`text-lg md:text-xl font-bold tracking-tight ${stat.positive ? 'text-green-600' : 'text-black'}`}>
                    {stat.value}
                  </h3>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Top Performing / Blue Tick Businesses */}
      {blueTickBusinesses.length > 0 && (
        <div className="mb-8">
          <h3 className="text-xl font-bold text-black mb-4 flex items-center space-x-2">
            <BadgeCheck size={24} className="text-blue-500" />
            <span>Top Performing / Verified Businesses</span>
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {blueTickBusinesses.map(b => (
              <div 
                key={`blue_${b.id}`} 
                onClick={() => setSelectedBusiness(b)}
                className="flex flex-col sm:flex-row sm:items-center justify-between p-4 bg-white border-2 border-blue-100 hover:border-blue-400 rounded cursor-pointer transition-all shadow-sm hover:shadow group gap-3 relative overflow-hidden"
              >
                <div className="absolute top-0 right-0 w-12 h-12 bg-blue-50 transform rotate-45 translate-x-6 -translate-y-6 group-hover:bg-blue-100 transition-colors"></div>
                
                <div className="flex items-center space-x-3 min-w-0 z-10">
                   <div className="w-10 h-10 rounded bg-blue-600 flex-shrink-0 text-white flex items-center justify-center font-black text-lg shadow-inner">
                     {b.name.charAt(0)}
                   </div>
                   <div className="min-w-0">
                     <div className="flex items-center space-x-1.5">
                       <h4 className="font-bold text-sm text-black group-hover:text-blue-700 transition-colors truncate">{b.name}</h4>
                       <BadgeCheck size={16} className="text-white fill-blue-500 flex-shrink-0" />
                     </div>
                     <p className="text-[11px] text-gray-500 mt-0.5 truncate uppercase tracking-wider leading-tight">{b.ownerName}</p>
                   </div>
                </div>
                <div className="text-right flex-shrink-0 z-10">
                  <div className="flex flex-col items-end">
                    <p className="text-[9px] text-gray-500 uppercase tracking-widest font-bold mb-0.5">Total Returns Info</p>
                    <p className="text-sm font-black text-green-600 block">{formatINR(b.totalRet)}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Other Listed Businesses (Verified) */}
      <div>
        <h3 className="text-xl font-bold text-black mb-4">Other Listed Businesses</h3>
        {otherBusinesses.length === 0 ? (
          <div className="p-8 text-center text-gray-500 text-sm font-medium">No businesses found.</div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
            {otherBusinesses.map(b => (
              <div 
                key={b.id} 
                onClick={() => setSelectedBusiness(b)}
                className="flex flex-col sm:flex-row sm:items-center justify-between p-3 bg-white border border-gray-200 hover:border-blue-300 rounded-lg cursor-pointer transition-all hover:shadow-sm group overflow-hidden gap-3"
              >
                <div className="flex items-center space-x-3 min-w-0">
                   <div className="w-8 h-8 rounded-full bg-blue-50 flex-shrink-0 text-blue-700 flex items-center justify-center font-bold text-sm">
                     {b.name.charAt(0)}
                   </div>
                   <div className="min-w-0">
                     <div className="flex items-center space-x-1">
                       <h4 className="font-bold text-xs text-black group-hover:text-blue-700 transition-colors truncate">{b.name}</h4>
                     </div>
                     <p className="text-[10px] text-gray-500 font-medium truncate">Owner: {b.ownerName}</p>
                   </div>
                </div>
                <div className="text-right flex-shrink-0">
                  <div className="text-[9px] font-bold text-green-700 bg-green-50 px-1.5 py-0.5 rounded inline-block mb-0.5 tracking-wide uppercase">{b.interestRate}% Return</div>
                  <p className="text-[11px] font-bold text-gray-900 mx-w-[80px] truncate">{formatINR(b.fundingRequired)}</p>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      <div className="grid grid-cols-1 gap-6 mt-6">
        <div className="bg-white border border-gray-200 rounded-lg p-5 shadow-sm">
          <h3 className="text-lg font-bold text-black mb-4">Recent Investments</h3>
          <div className="space-y-3">
            {recentFilteredInvestments.slice(0, 5).map(inv => {
              const business = state.businesses.find(b => b.id === inv.businessId);
              const investor = state.investors.find(i => i.id === inv.investorId);
              return (
                <div key={inv.id} className="p-3 bg-gray-50 rounded-lg flex flex-col md:flex-row md:items-center justify-between border border-gray-100">
                  <div className="mb-2 md:mb-0">
                    <div className="flex items-center space-x-2">
                      <p className="font-bold text-black text-sm">{investor?.name}</p>
                    </div>
                    <div className="flex items-center text-xs text-gray-600 mt-1">
                      <span>Invested in <span className="font-semibold text-gray-900">{business?.name}</span></span>
                      {business && blueTickBusinessIds.has(business.id) && <BadgeCheck size={12} className="text-blue-500 ml-1" />}
                    </div>
                  </div>
                  
                  <div className="flex items-center space-x-4 text-right">
                    <div>
                      <p className="text-[10px] font-bold text-gray-400 uppercase tracking-wider">Amount</p>
                      <p className="font-black text-black text-base">{formatINR(inv.amount)}</p>
                    </div>
                    <div className="hidden sm:block text-right">
                      <p className="text-[10px] font-bold text-gray-400 uppercase tracking-wider">Interest</p>
                      <p className="font-bold text-green-600 text-sm">{inv.interestRate}%</p>
                    </div>
                    <div className="hidden sm:block">
                       <span className="inline-flex items-center px-2 py-0.5 rounded bg-green-100 text-green-800 text-[10px] font-bold tracking-wide uppercase">
                        {inv.status}
                      </span>
                    </div>
                  </div>
                </div>
              );
            })}
            {recentFilteredInvestments.length === 0 && (
              <div className="p-6 text-center text-gray-500 text-sm font-medium border border-gray-200 border-dashed rounded-xl">No investments found.</div>
            )}
          </div>
        </div>
      </div>

      {selectedBusiness && renderBusinessDetails(selectedBusiness)}
    </div>
  );
}

